name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout the output branch
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ishaa05
          outputs: dist/snake.svg

      # Push the generated snake animation to the output branch
      - name: Push to output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
