name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ishaa05
          outputs: dist/snake.svg

      # Step 3: Push the snake animation to the repository
      - name: Upload the snake animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
