name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Critical: allows writing to repository
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit  # Force commit changes
          committer_branch: main
          committer_message: Update README stats
          base: "repositories, metadata"
          config_display: large
          config_timezone: Asia/Dubai
          
      - name: Debug Output
        run: |
          echo "Checking repository contents"
          ls -la
